
Multi-armed bandits is a rich, multi-disciplinary research area which receives attention from computer science, operations research, economics and statistics. It has been studied since (Thompson, 1933), with a big
surge of activity in the past 15-20 years


Other sources:
    * https://tor-lattimore.com/downloads/book/book.pdf by lattimore2020bandit by 
    * Intro to Multi-Armed Bandits slivkins2019introduction
@book{lattimore2020bandit,
  title={Bandit algorithms},
  author={Lattimore, Tor and Szepesv{\'a}ri, Csaba},
  year={2020},
  publisher={Cambridge University Press}
}
          
@article{slivkins2019introduction,
  title={Introduction to multi-armed bandits},
  author={Slivkins, Aleksandrs and others},
  journal={Foundations and Trends{\textregistered} in Machine Learning},
  volume={12},
  number={1-2},
  pages={1--286},
  year={2019},
  publisher={Now Publishers, Inc.}
}
    
@article{thompson1933likelihood,
  title={On the likelihood that one unknown probability exceeds another in view of the evidence of two samples},
  author={Thompson, William R},
  journal={Biometrika},
  volume={25},
  number={3-4},
  pages={285--294},
  year={1933},
  publisher={Oxford University Press}
}

# Multi-Armed Bandit Problem

## Introduction

The Multi-Armed Bandit (MAB) problem is a classical reinforcement learning problem that exemplifies the exploration-exploitation trade-off. The goal is to maximize the cumulative reward by choosing the best arm to pull at each time step.

## Formal Definition

A multi-armed bandit problem can be formally defined as follows:
- **Arms**: A set of $K$ arms, where each arm $i$ provides a reward from an unknown probability distribution $P_i$.
- **Time Steps**: The agent interacts with the bandit over a sequence of $T$ time steps.
- **Rewards**: At each time step $t$, the agent selects an arm $a_t$ and receives a reward $r_t$ drawn from the distribution $P_{a_t}$.

The objective is to maximize the expected cumulative reward over $T$ time steps.

POssible applications; 
a crowdsourcing platform can improve the assignment of tasks, workers and prices

## Key Concepts

### Exploration vs. Exploitation

- **Exploration**: Trying different arms to gather information about their reward distributions.
- **Exploitation**: Selecting the arm with the highest known reward based on the information gathered so far.

Balancing these two aspects is crucial for achieving optimal performance in the MAB problem.

### Regret

Regret measures the difference between the cumulative reward obtained by the optimal strategy and the reward obtained by the algorithm. It is defined as:

$$
R(T) = T \mu^* - \sum_{t=1}^T \mu_{a_t}
$$

where $\mu^*$ is the mean reward of the best arm, and $\mu_{a_t}$ is the mean reward of the arm chosen at time $t$.

## Strategies for Multi-Armed Bandit Problems

### 1. Epsilon-Greedy

The epsilon-greedy strategy is one of the simplest approaches:
- With probability $\epsilon$, select a random arm (exploration).
- With probability $1 - \epsilon$, select the arm with the highest average reward observed so far (exploitation).

In [1]:
import numpy as np

class EpsilonGreedy:
    def __init__(self, n_arms, epsilon):
        self.n_arms = n_arms
        self.epsilon = epsilon
        self.counts = np.zeros(n_arms)
        self.values = np.zeros(n_arms)
    
    def select_arm(self):
        if np.random.rand() < self.epsilon:
            return np.random.randint(0, self.n_arms)
        else:
            return np.argmax(self.values)
    
    def update(self, chosen_arm, reward):
        self.counts[chosen_arm] += 1
        n = self.counts[chosen_arm]
        value = self.values[chosen_arm]
        self.values[chosen_arm] = ((n - 1) / n) * value + (1 / n) * reward

# Example usage
n_arms = 10
epsilon = 0.1
n_rounds = 1000

bandit = EpsilonGreedy(n_arms, epsilon)
rewards = np.random.rand(n_arms)  # Simulated rewards for each arm

for _ in range(n_rounds):
    chosen_arm = bandit.select_arm()
    reward = rewards[chosen_arm]
    bandit.update(chosen_arm, reward)

print("Estimated values:", bandit.values)


Estimated values: [0.68938076 0.30039331 0.31864242 0.55685491 0.63974092 0.16368959
 0.20460775 0.32663808 0.3753893  0.6461065 ]


### Uppder Confidence Bound (UCB)
The UCB algorithm selects the arm that maximizes the upper confidence bound of the reward estimate. For each arm $i$, the upper confidence bound is calculated as:
$$
UCB_i (t) = \hat{\mu}_i + \sqrt{\frac{2 \ln t}{n_i}}
$$

In [2]:
class UCB1:
    def __init__(self, n_arms):
        self.n_arms = n_arms
        self.counts = np.zeros(n_arms)
        self.values = np.zeros(n_arms)
    
    def select_arm(self):
        total_counts = np.sum(self.counts)
        if 0 in self.counts:
            return np.argmin(self.counts)
        else:
            ucb_values = self.values + np.sqrt((2 * np.log(total_counts)) / self.counts)
            return np.argmax(ucb_values)
    
    def update(self, chosen_arm, reward):
        self.counts[chosen_arm] += 1
        n = self.counts[chosen_arm]
        value = self.values[chosen_arm]
        self.values[chosen_arm] = ((n - 1) / n) * value + (1 / n) * reward

# Example usage
bandit = UCB1(n_arms)

for _ in range(n_rounds):
    chosen_arm = bandit.select_arm()
    reward = rewards[chosen_arm]
    bandit.update(chosen_arm, reward)

print("Estimated values:", bandit.values)


Estimated values: [0.68938076 0.30039331 0.31864242 0.55685491 0.63974092 0.16368959
 0.20460775 0.32663808 0.3753893  0.6461065 ]


### Thompson Sampling
Thompson Sampling is a Bayesian approach to the MAB problem:

- Maintain a probability distribution (prior) over the possible reward distributions of each arm.
- At each time step, sample from these distributions (posterior) and select the arm with the highest sampled value.
- Update the posterior distributions based on the observed rewards.

In [3]:
class ThompsonSampling:
    def __init__(self, n_arms):
        self.n_arms = n_arms
        self.successes = np.zeros(n_arms)
        self.failures = np.zeros(n_arms)
    
    def select_arm(self):
        samples = np.random.beta(self.successes + 1, self.failures + 1)
        return np.argmax(samples)
    
    def update(self, chosen_arm, reward):
        if reward == 1:
            self.successes[chosen_arm] += 1
        else:
            self.failures[chosen_arm] += 1

# Example usage
bandit = ThompsonSampling(n_arms)

for _ in range(n_rounds):
    chosen_arm = bandit.select_arm()
    reward = np.random.binomial(1, rewards[chosen_arm])  # Simulated binary reward
    bandit.update(chosen_arm, reward)

print("Successes:", bandit.successes)
print("Failures:", bandit.failures)


Successes: [ 61.   5.   4.  35. 329.   3.   0.   3.  11. 154.]
Failures: [ 41.   9.  10.  31. 167.   8.   6.   9.  17.  97.]


## Variants of the Multi-Armed Bandit Problem
### Contextual Bandits
In contextual bandits, the decision-making process is conditioned on the context $x_t$ available at each time step $t$. The objective is to learn a policy that maps contexts to arms, maximizing the cumulative reward.

In [4]:
class ContextualBandit:
    def __init__(self, n_arms, n_features):
        self.n_arms = n_arms
        self.n_features = n_features
        self.beta = np.zeros((n_arms, n_features))
    
    def select_arm(self, context):
        means = context @ self.beta.T
        return np.argmax(means)
    
    def update(self, chosen_arm, context, reward):
        x = context
        self.beta[chosen_arm] += (reward - x @ self.beta[chosen_arm]) * x

# Example usage
n_features = 5
contextual_bandit = ContextualBandit(n_arms, n_features)
contexts = np.random.rand(n_rounds, n_features)  # Simulated contexts

for t in range(n_rounds):
    context = contexts[t]
    chosen_arm = contextual_bandit.select_arm(context)
    reward = rewards[chosen_arm]  # Simulated reward based on context
    contextual_bandit.update(chosen_arm, context, reward)

print("Estimated beta values:", contextual_bandit.beta)


Estimated beta values: [[-0.7261821  -0.59311302 -0.14791038 -0.18479997 -0.56418083]
 [-0.26553296 -0.6293445   0.02559575  0.03434534 -0.21331706]
 [ 0.06694129  0.28175289  0.3263419  -0.15662175  0.38866766]
 [-0.27852281 -0.4379015  -0.24835678 -0.64751958 -0.69561334]
 [-0.78417637  0.02071664 -0.15410988  0.01556134 -0.88819534]
 [-0.05779773 -0.32515711 -0.09882127  0.28491598 -0.12559452]
 [-0.15317811 -0.27006679 -0.18948673 -0.04745555 -0.08103359]
 [ 0.55694393 -0.48739759 -0.01252385 -0.4317254  -0.38838356]
 [-0.17268967 -0.2423782  -0.27177583 -0.09475155 -0.11100693]
 [-0.34478075 -0.13146383 -0.54009013  0.05728585 -1.14187497]]


### Non-Stationary Bandits
Non-stationary bandits consider scenarios where the reward distributions of the arms change over time. Algorithms for this variant need to adapt to these changes, often incorporating mechanisms for discounting past observations or detecting change points.

### Combinatorial Bandits
Combinatorial bandits involve selecting subsets of arms rather than a single arm at each time step. This variant is relevant in scenarios where the decision-maker must allocate resources across multiple options simultaneously.

## Applications
The multi-armed bandit problem has numerous real-world applications, including:

- Online Advertising: Selecting which ads to display to maximize click-through rates.
- Clinical Trials: Allocating treatments to patients to identify the most effective treatment.
- Recommendation Systems: Presenting items (e.g., movies, products) to users to maximize engagement.
